version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    volumes:
      - .:/src
      - /src/DietManagementSystem.API/bin
      - /src/DietManagementSystem.API/obj 